env: dev

wmx_database:
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_NAME: "wmx"
  DB_USER: "root"
  DB_PASSWORD: "zeus@CC1234!"

#task:
#  model_path: "./bge-large-zh-v1.5"
#  port: 8001


vector_service:
  model_path: "./bge-large-zh-v1.5"
  port: 8001
  redis_broker: "redis://127.0.0.1:6379/0"
  redis_backend: "redis://127.0.0.1:6379/1"



elasticsearch:
  host: "http://127.0.0.1:9200"
  knowledge_base: "zhisk_results"
  question_base: "wmx_ques"
  username: "elastic"       # 若无需认证，可为空
  password: "wlw123456"       # 若需加密访问，可以加密
  indexes:
    file_index: "zhisk_files"
    chunk_index: "zhisk_results"
    ques_index: "wmx_ques"
    sensitive_index: "sensitive_terms"


task_defaults:
  store_flags: ["es"]   # 控制写入目标，示例 tore_flags: ["pg", "es"]
  pg_enable: false
  es_enable: true

session_cache:
  redis_url: redis://localhost:6379/2
  expire_seconds: 3600

deepseek:
  api_key: "sk-3aad58df7dc442b6995921263f6c953f"
  base_url: "https://api.deepseek.com"


qwen:
  api_key: "sk-e8d4973beecd4a43bdce4718b0b2444c"
  model: "qwen-plus"

sensitive:
  ignore_case: false         # 是否大小写不敏感
  page_size: 2000            # ES 分页拉取大小（大词库用）
  max_single_fetch: 10000    # 小词库阈值；≤该值时一次性拉
  enable_input_block: true   # 是否启用输入拦截中间件
  check_fields:              # 输入拦截检查的字段（按你的接口字段定）
    - question
    - filename
    - new_content
    - new_question
    - title


ocr_service:
  base_url: "http://172.16.19.61:8181"   # 你的OCR服务器地址